# Generated by Django 5.2.6 on 2025-09-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id_legacy', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('office', models.CharField(blank=True, max_length=200)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_seniority_years', models.IntegerField()),
                ('max_seniority_years', models.IntegerField()),
                ('allotted_vacation_days', models.IntegerField()),
            ],
            options={
                'ordering': ['min_seniority_years'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('workdays_deducted', models.IntegerField(default=0)),
                ('holiday_leave_deducted', models.IntegerField(default=0)),
                ('cct_days_deducted', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave.employee')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('allotted_workdays', models.IntegerField(default=0)),
                ('allotted_holiday_leave', models.IntegerField(default=0)),
                ('allotted_cct_days', models.IntegerField(default=0)),
                ('carried_over_workdays', models.IntegerField(default=0)),
                ('carried_over_holiday_leave', models.IntegerField(default=0)),
                ('carried_over_cct_days', models.IntegerField(default=0)),
                ('taken_workdays', models.IntegerField(default=0)),
                ('taken_holiday_leave', models.IntegerField(default=0)),
                ('taken_cct_days', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='leave.employee')),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
