# Generated by Django 5.2.6 on 2025-09-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavebalance_business_days_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_cct_leave',
            field=models.BooleanField(default=True),
        ),
    ]
