# Generated by Django 5.2.6 on 2025-09-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_is_cct_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='proof_documents/'),
        ),
    ]
